version: "3"
services:
  api:
    build:
      context: .
    environment:
      VIRTUAL_HOST: patientapp.ncasola.cloud
      LETSENCRYPT_HOST: patientapp.ncasola.cloud
      LETSENCRYPT_EMAIL: ncasolajimenez@gmail.com

networks:
  default:
    external:
      name: proxy
